### ISSUE TITLE
Course Curriculum Checklist

### ISSUE THREAD

**Issue by sudomateo** [sudomateo/terraform-training#1]
# Course Curriculum

## 01 Getting Started

Install Terraform and familiarize yourself with your cloud provider.

- [x] What is Terraform?
- [x] How does Terraform work?
- [x] Why use Terraform?
- [x] Terraform Installation
- [x] Editor Configuration
- [x] Cloud Provider Configuration

## 02 Terraform Basics

Learn the Terraform configuration syntax and use Terraform to provision infrastructure. 

- [x] Configuration Syntax
- [x] The Core Workflow
- [x] Modifying Infrastructure
- [x] Terraform State
- [x] Destroying Infrastructure

## 03 Terraform Language

Use all of the top-level configuration keywords in Terraform.

- [x] Providers
- [x] Resources
- [x] Data Sources
- [x] Variables
- [x] Outputs
- [x] Locals

## 04 Provisioners

Use Provisioners to extend Terraform with imperative workflows.

- [x] What are Provisioners?
- [x] Declaring Provisioners
- [x] The `local-exec` Provisioner
- [x] The `remote-exec` Provisioner
- [x] The `file` Provisioner
- [x] Provisioners Without a Resource
- [x] Alternatives to Provisioners

## 05 Modules

Create reusable abstractions of Terraform configuration using Modules.

- [x] What are Modules?
- [x] Using Modules
- [x] Developing Modules
- [x] Providers in Modules
- [x] Module Sources
- [x] Publishing Modules to the Terraform Registry

## 06 State Management

Understand and interact with Terraform state.

- [x] Inspecting Infrastructure
- [x] Importing Infrastructure
- [x] Manipulating State
- [x] Refreshing State
- [x] The `terraform_remote_state` Data Source
- [x] Understanding Secrets in State

## 07 State Backends

Store Terraform state securely and prevent state corruption with state locking.

- [x] The Local Backend
- [x] Remote Backends
- [x] Configuring Remote State Storage
- [x] State Locking
- [x] Configuring Remote State Locking
- [x] Migrating State Between Backends

## 08 Workspaces

Deploy a clone of your infrastructure using Workspaces.

- [x] What are Workspaces?
- [x] Avoiding Infrastructure Collisions
- [x] Using Workspaces
- [x] Alternatives to Workspaces

## 09 Advanced Terraform Configuration

Use advanced Terraform features to DRY up your configuration and scale deployments.

- [x] Functions
- [x] Expressions
- [x] Scaling with `count`
- [x] Scaling with `for_each`
- [x] Dynamic Blocks
- [x] Custom Conditions
- [x] Terraform Console
- [x] Override Files

## 10 Terraform in Automation

Integrate Terraform with your CI/CD workflows.

- [x] Verifying Terraform Configuration
- [x] Running Terraform in CI/CD
- [x] Terraform CLI Configuration
- [x] Using Custom Providers
- [x] Debugging Terraform
- [x] Tuning Terraform

## 11 Terraform Cloud & Terraform Enterprise

Extend Terraform with features from Terraform Cloud and Terraform Enterprise.

- [x] What is Terraform Cloud and Terraform Enterprise?
- [x] VCS-driven Runs
- [x] CLI-driven Runs
- [x] API-driven Runs
- [x] Private Module Registry
- [x] Team, Governance, and Business Features

## 12 Developing a Terraform Provider

Integrate Terraform with an API by developing a custom Terraform provider.

- [x] Making CRUD Requests to an API
- [x] Terraform Plugin Framework
- [x] Building a Go SDK for the API
- [x] Implement a Data Source
- [x] Implement Create and Read
- [x] Implement Update
- [x] Implement Delete
- [x] Implement Import
